apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:  
  selector:
    app: kafka-ui
  ports:
    - name: kafka-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      name: kafka-ui
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
          name: kafka-ui
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "kafka"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "192.168.49.2:30032"