---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: consumerbackend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumerbackend
    spec:
      containers:
      - name: consumerbackend
        image: maltesius/consumerimage:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: consumerbackend
---
apiVersion: v1
kind: Service
metadata:
  name: consumerbackend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: consumerbackend
